apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mky-cd # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  wait: true
  interval: 600s
  path: clusters/wac-aks
  prune: true
  sourceRef:
    kind: GitRepository
    name: mky-gitops-repo
