kind: Service
apiVersion: v1
metadata:
  name: mky-openapi-ui
spec:
  selector:
    pod: mky-ambulance-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
